### PR TITLE
Remove scale argument for loader and require units for map viewport size

### PR DESCRIPTION
**Pull request by nvaytet**
Removes the `scale="au"` argument when loading data.
We now rely on scaling in maps, e.g. `dx=200*au` and no longer support window size without a unit: `dx=200`.

### CODE REVIEW

**Review by Adnan-Ali-Ahmad — APPROVED** [review]
Works great!

**Comment by haugboel** [comment]
Yes, looks good. I also notice that you seem to have removed more lines than added, which is another indicator this was a reasonable change. Simplifying things is usually better. And special cases (“scale”) are not.

**Comment by nvaytet** [comment]
I think most of the deleted lines come from the fact that I also deleted an old file that was used to convert ramses data to VTK files. It was outdated an unusable with the current version of osyris.
We can add it back in at a later stage if that is something people would like to have.

All that said, yes, deleting stuff is always good ;-)

**Comment by nvaytet** [comment]
Before this change if you tried to make a `map` with `dx=0.01*pc` after having used `scaled="au"` it would actually fail.
So this is also fixing something ;-)

**Pull request merged**
